title: Bingchen Li
description: My academic homepage and research projects
baseurl: ""
url: "https://bingchen054.github.io"

remote_theme: Jasper0122/academic-homepage

markdown: kramdown
plugins:
  - jekyll-email-protect
  - jekyll-seo-tag

collections:
  publications:
  news:
  showcase:
  projects:
